name: First Workflow
on: [push,workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: get the code
      uses: actions/checkout@v4
    - name: composer
      run: php composer.phar install
    - name: build the code
      run: php -l index.php
    - name: deploy
      run: echo "Deploying ..."
